# Generated by Django 4.2.2 on 2023-08-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_photo_10_remove_listing_photo_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Townhouse', 'Townhouse'), ('Condo', 'Condo')], default='House', max_length=50),
        ),
    ]
